# Generated by Django 3.2.4 on 2021-06-11 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description_short', models.TextField(max_length=255)),
                ('description_long', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/%Y/m/')),
                ('slug', models.SlugField(unique=True)),
                ('price_marketing', models.FloatField()),
                ('price_marketing_promo', models.FloatField(default=0)),
                ('type', models.CharField(choices=[('v', 'variation '), ('s', 'simple')], default='v', max_length=1)),
            ],
        ),
    ]
