# Generated by Django 3.2.4 on 2021-06-13 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210613_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='nome',
            new_name='name',
        ),
    ]
